name: Deployment of NxtGen Spring Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Deployment of NxtGen Spring Application
    runs-on: ubuntu-latest
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v3     

      - name: Install Java  JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build NxtGen Application
        run: mvn -b build --file pom.xml

      - name: Test NxtGen Application
        run: mvn -B test --file pom.xml
