name: Deployment of NxtGen Spring Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Deployment of NxtGen Spring Application
    runs-on: ubuntu-latest
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Install Java  JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Test NxtGen Application
        run: mvn -B test --file pom.xml

      - name: Build & Package NxtGen Application
        run: |
          mvn -B clean
          mvn -B package  --file pom.xml

      - name: Build NxtGen Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.GIT_ACTIONS_DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.GIT_ACTIONS_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.GITACTION_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push NxtGen Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.GIT_ACTIONS_DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest

      - name: SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@v2.2
        with:
          sonar-host-url: ${{ secrets.NXTGEN_SONAR_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_GITHUB_ACTION_TOKEN }}
          sonar-project-key: Spring-Boot
